CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UNIQUE_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(500)                            NOT NULL,
    category           BIGINT                                  NOT NULL,
    description        VARCHAR(5000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    lat                FLOAT8                                  NOT NULL,
    lon                FLOAT8                                  NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  BIGINT                                  NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    title              VARCHAR(2000)                           NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    state              VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT FK_INITIATOR_ON_USER FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT FK_CATEGORY_ON_CATEGORY_ID FOREIGN KEY (category) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pined BOOLEAN                                 NOT NULL,
    title VARCHAR(1000)                           NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       BIGINT                                  NOT NULL,
    compilation_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_events_compilations PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ON_EVENT_ID FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_COMPILATION_ON_COMPILATION_ID FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(100)                            NOT NULL,
    CONSTRAINT FK_EVENT_ID_ON_EVENTS_ID FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_REQUESTER_ID_ON_USERS_ID FOREIGN KEY (requester_id) REFERENCES users (id)
);









