CREATE TABLE IF NOT EXISTS hits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app           VARCHAR(100)                            NOT NULL,
    uri           VARCHAR(1000)                           NOT NULL,
    ip            VARCHAR(100)                            NOT NULL,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);